[package]
name = "ibuki"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
base64 = "0.22.1"
flume = "0.11.1"
dashmap = "6.1.0"
dotenv = "0.15.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
futures = "0.3.31"
async-trait = "0.1.88"
serde_json = "1.0.140"
tower = "0.5.2"
byteorder = "1.5.0"

[dependencies.uuid]
version = "1.16.0"
features = ["v4", "v7"]

[dependencies.reqwest]
version = "0.11.27"
default-features = false
features = ["json"]

[dependencies.tokio]
version = "1.44.1"
features = ["tracing", "macros", "signal", "rt-multi-thread"]

[dependencies.songbird]
default-features = false
features = ["driver", "tungstenite", "rustls"]
version = "0.5.0"

[dependencies.symphonia]
version = "0.5.4"
features = ["all"]

[dependencies.axum]
default-features = true
features = ["ws"]
version = "0.8.3"

[dependencies.serde]
version = "1.0.219"
features = ["derive"]
