[package]
name = "ibuki"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
flume = "0.11.1"
dashmap = "6.1.0"
dotenv = "0.15.0"
tracing = "0.1.41"
futures = "0.3.31"
async-trait = "0.1.88"

[dependencies.uuid]
version = "1.16.0"
features = ["v4", "v7"]

[dependencies.reqwest]
version = "0.11.27"
default-features = false
features = ["json"]

[dependencies.tokio]
version = "1.44.1"
features = ["tracing", "macros", "signal", "rt-multi-thread"]

[dependencies.songbird]
default-features = false
features = ["driver", "simd-json", "rustls"]
version = "0.4.6"

[dependencies.axum]
default-features = true
features = ["ws"]
version = "0.8.3"
