name: Manual Deployment
on:
  workflow_dispatch

jobs:
  build-windows-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set rustup default toolchain
      run: rustup default nightly-x86_64-pc-windows-msvc
    
    - name: Build executable
      run: cargo build --release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4

      with:
        name: ${{ github.job }}-windows-x64
        path: ./target/release/ibuki.exe
        compression-level: 0
        
  build-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get install -y gcc-multilib

      - name: Set rustup default toolchain
        run: rustup default nightly-x86_64-unknown-linux-gnu

      - name: Build executable
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}-x86_64-unknown-linux-gnu
          path: ./target/release/ibuki
          compression-level: 0